import Head from 'next/head'
import Header from '../components/Header'
import { Container } from '../components/styled/Container.styled'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Header />
      <Container>
      </Container>
    </div>
  )
}
